name: 'Maven build process'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 17
          maven-version: 3.9.11
      - name: Maven SpringBoot Build
        env:
          APIKEY: ${{ secrets.ApiKey }}
        run: mvn -V -B -f weather-forecast-springboot/pom.xml package
      - name: Maven Quarkus Build
        env:
          APIKEY: ${{ secrets.ApiKey }}
        run: mvn -V -B -f weather-forecast-quarkus/pom.xml -Dquarkus.profile=prod package